project_id = "unlkencwjcnlworjeexw"

[functions.create-payment]
verify_jwt = false

[functions.verify-payment]
verify_jwt = false

[functions.create-test-user]
verify_jwt = false

[functions.mercadopago-webhook]
verify_jwt = false

[functions.whatsapp-notify]
verify_jwt = false
